/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MoroccanBathRouteImport } from './routes/moroccan-bath'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogWhatIsAMoroccanBathHammamRouteImport } from './routes/blog.what-is-a-moroccan-bath-hammam'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MoroccanBathRoute = MoroccanBathRouteImport.update({
  id: '/moroccan-bath',
  path: '/moroccan-bath',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWhatIsAMoroccanBathHammamRoute =
  BlogWhatIsAMoroccanBathHammamRouteImport.update({
    id: '/blog/what-is-a-moroccan-bath-hammam',
    path: '/blog/what-is-a-moroccan-bath-hammam',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/moroccan-bath': typeof MoroccanBathRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/what-is-a-moroccan-bath-hammam': typeof BlogWhatIsAMoroccanBathHammamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/moroccan-bath': typeof MoroccanBathRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/what-is-a-moroccan-bath-hammam': typeof BlogWhatIsAMoroccanBathHammamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/moroccan-bath': typeof MoroccanBathRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/what-is-a-moroccan-bath-hammam': typeof BlogWhatIsAMoroccanBathHammamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/moroccan-bath'
    | '/privacy'
    | '/sitemap.xml'
    | '/blog/what-is-a-moroccan-bath-hammam'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/moroccan-bath'
    | '/privacy'
    | '/sitemap.xml'
    | '/blog/what-is-a-moroccan-bath-hammam'
  id:
    | '__root__'
    | '/'
    | '/moroccan-bath'
    | '/privacy'
    | '/sitemap.xml'
    | '/blog/what-is-a-moroccan-bath-hammam'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MoroccanBathRoute: typeof MoroccanBathRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogWhatIsAMoroccanBathHammamRoute: typeof BlogWhatIsAMoroccanBathHammamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moroccan-bath': {
      id: '/moroccan-bath'
      path: '/moroccan-bath'
      fullPath: '/moroccan-bath'
      preLoaderRoute: typeof MoroccanBathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/what-is-a-moroccan-bath-hammam': {
      id: '/blog/what-is-a-moroccan-bath-hammam'
      path: '/blog/what-is-a-moroccan-bath-hammam'
      fullPath: '/blog/what-is-a-moroccan-bath-hammam'
      preLoaderRoute: typeof BlogWhatIsAMoroccanBathHammamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MoroccanBathRoute: MoroccanBathRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogWhatIsAMoroccanBathHammamRoute: BlogWhatIsAMoroccanBathHammamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
